# Site author
site_author: Sergei Tilipin

# Site description
site_description: >-
  Blog about automation, configuration, and optimization of WSL environments and Linux systems.

# Site name
site_name: GreenGorych

# Site URL
site_url: https://greengorych.io

# Copyright setting
copyright: >-
  Â© 2025 Sergei Tilipin.
  Texts licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/" title="CC BY-SA 4.0" target="_blank">CC BY-SA 4.0</a>,
  code examples under <a href="https://opensource.org/licenses/MIT" title="MIT" target="_blank">MIT</a>.
  <a href="#__consent" title="Change cookie settings">Change cookie settings.</a>

# Theme settings
theme:
  # Theme name
  name: material
  # Site favicon
  favicon: assets/images/leaf.svg
  # Theme features
  features:
    # Enables adding comments to sections of a code block
    - content.code.annotate
    # Enables the button to copy a block of code
    - content.code.copy
    # Enables the button for selecting lines in a code block (Insiders version only)
    # - content.code.select
    # Automatically hide the header when scrolling
    - header.autohide
    # Expand navigation sections
    - navigation.expand
    # Enables or disables footer navigation
    - navigation.footer
    # Use section index pages
    # - navigation.indexes
    # Enable instant loading between pages
    - navigation.instant
    # Enable instant prefetching (preload linked pages)
    # - navigation.instant.prefetch
    # Enable instant previews
    # - navigation.instant.preview
    # Show a progress indicator during page loads
    - navigation.instant.progress
    # Display the navigation path (breadcrumbs)
    # - navigation.path
    # Prune navigation to only show relevant sections
    # - navigation.prune
    # Group pages by navigation sections
    - navigation.sections
    # Display navigation tabs
    # - navigation.tabs
    # Make navigation tabs sticky on scroll
    # - navigation.tabs.sticky
    # Show a back-to-top button
    - navigation.top
    # Track the active anchor in navigation
    - navigation.tracking
    # Show search suggestions
    - search.suggest
    # Highlight matching searching terms
    - search.highlight
    # Add a button to share the current search URL
    - search.share
    # Follow the active anchor in the table of contents
    - toc.follow
    # Integrate table of contents into the navigation sidebar
    - toc.integrate
  # Icons settings
  icon:
    # Admonition icons
    admonition:
      # Abstract icon
      abstract: material/book-outline
      # Bug icon
      bug: material/bug-outline
      # Danger icon
      danger: material/skull-outline
      # Example icon
      example: material/flask-outline
      # Failure icon
      failure: material/close-octagon-outline
      # Info icon
      info: material/information-outline
      # Note icon
      note: material/note-text-outline
      # Question icon
      question: material/help-circle-outline
      # Quote icon
      quote: material/format-quote-close-outline
      # Success icon
      success: material/check-circle-outline
      # Tip icon
      tip: material/lightbulb-on-outline
      # Warning icon
      warning: material/alert-outline
    # Interface icons
    # Change language icon
    # alternate: material/translate
    # Close icon
    close: material/close
    # Edit current page icon
    edit: material/file-edit-outline
    # Logo icon
    logo: material/leaf
    # Mobile menu icon
    menu: material/menu
    # Next page in footer icon
    next: material/arrow-right
    # Previous page in footer icon
    previous: material/arrow-left
    # Header repository icon
    repo: material/git
    # Search icon
    search: material/magnify
    # Share search icon
    share: material/share
    # Back-to-top button icon
    top: material/arrow-up
    # View page source icon
    view: material/file-eye-outline

  # Theme color palette settings
  palette:
    # Color palette configuration for automatic mode
    - media: "(prefers-color-scheme)"
      # Toggle settings for automatic mode
      toggle:
        # Icon displayed when automatic mode is selected
        icon: material/link
        # Tooltip shown when hovering over the toggle button
        name: Switch to light mode

    # Color palette configuration for light mode
    - media: "(prefers-color-scheme: light)"
      # Accent color for interactive elements (links, highlights, etc.)
      accent: indigo
      # Primary theme color used for header, footer, sidebar, etc.
      primary: indigo
      # Name of the light color scheme
      scheme: default
      # Toggle settings for light mode
      toggle:
        # Icon displayed when light mode is selected
        icon: material/toggle-switch
        # Tooltip shown when hovering over the toggle button
        name: Switch to dark mode

    # Color palette configuration for dark mode
    - media: "(prefers-color-scheme: dark)"
      # Accent color for interactive elements (links, highlights, etc.)
      accent: indigo
      # Primary theme color used for header, footer, sidebar, etc.
      primary: black
      # Name of the dark color scheme
      scheme: slate
      # Toggle settings for dark mode
      toggle:
        # Icon displayed when dark mode is selected
        icon: material/toggle-switch-off
        # Tooltip shown when hovering over the toggle button
        name: Switch to system preference

  # Font settings
  font:
    # Text font
    text: Roboto
    # Code blocks font
    code: Roboto Mono
  # Site language
  language: en
  # Site language direction
  direction: ltr

# Plugins settings
plugins:
  # Blog plugin settings
  - blog:
      # Enables or disables blog archive
      archive: true
      # Specifies archive sections date format
      archive_date_format: yyyy
      # Specifies the name of the archive section
      archive_name: Archive
      # Enables or disables archive pagination (Insiders version only)
      # archive_pagination: false
      # Specifies archive pagination per page (Insiders version only)
      # archive_pagination_per_page: 5
      # Shows post titles in archive section
      archive_toc: false
      # Specifies archive URL format
      archive_url_format: "archive/{date}"
      # Specifies archive URL date format
      # archive_url_date_format: yyyy
      # Enables or disables showing authors in blog posts
      authors: true
      # Configuration with blog post authors settings
      authors_file: "{blog}/.authors.yml"
      # Enables or disables authors profiles (Insiders version only)
      # authors_profiles: true
      # Authors profile name (Insiders version only)
      # authors_profiles_name: Authors
      # Enables or disables authors profiles pagination (Insiders version only)
      # authors_profiles_pagination: false
      # Authors profiles pagination per page (Insiders version only)
      # authors_profiles_pagination_per_page: 5
      # Enables or disables showing authors table of contents (Insiders version only)
      # authors_profiles_toc: false
      # Defines authors profiles URL format (Insiders version only)
      # authors_profiles_url_format: "author/{slug}"
      # Directory with blog posts
      blog_dir: .
      # Shows post titles on blog section
      blog_toc: false
      # Enables or disables categories
      categories: true
      # List of allowed categories
      categories_allowed:
        - General
        - Ubuntu
        - WSL
      # Specifies the name of the category section
      categories_name: Categories
      # Enables or disables pagination for category pages (Insiders version only)
      # categories_pagination: false
      # Sets the number of posts per category page in pagination (Insiders version only)
      # categories_pagination_per_page: 5
      # Converts category page URLs to uppercase or lowercase
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      # Sets the slug separator for category URLs
      categories_slugify_separator: "-"
      # Sets the category sorting rule (Insiders version only)
      # categories_sort_by: !!python/name:material.plugins.blog.view_post_count
      # Enables or disables reverse sorting of categories (Insiders version only)
      # categories_sort_reverse: true
      # Shows post titles on categories (inherited from blog_toc if not set explicitly)
      categories_toc: false
      # Category pages URL pattern
      categories_url_format: "category/{slug}"
      # Enable blog plugin
      enabled: true
      # Blog posts date format
      post_date_format: long
      # Blog posts directory
      post_dir: "posts"
      # Sets a required or optional post excerpt
      post_excerpt: required
      # Sets the number of authors in a post excerpt
      post_excerpt_max_authors: 1
      # Sets the number of categories in a post excerpt
      post_excerpt_max_categories: 2
      # Sets the separator to define the post excerpt
      post_excerpt_separator: <!-- more -->
      # Show blog post read time
      post_readtime: true
      # Sets the number of words read per minute.
      post_readtime_words_per_minute: 300
      # Converts blog posts page URLs to uppercase or lowercase
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      # Sets the slug separator for blog post URLs
      post_slugify_separator: "-"
      # URLs date pattern for blog posts
      # post_url_date_format: yyyy/MM/dd
      # URLs pattern for blog posts
      post_url_format: "blog/{slug}"
      # Sets the number of categories included in the blog post URL
      post_url_max_categories: 2
  # Search plugin settings
  - search:
      # Enable search plugin
      enabled: true
      # Search language
      lang: en
      # Search separators (regular expression for splitting text into tokens)
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      # Search pipeline with text processing stages
      pipeline:
        # Reduces words to their base form
        - stemmer
        # Removes common stop words
        - stopWordFilter
        # Trims punctuation and special characters
        - trimmer

# Additional settings
extra:
  # Cookie consent configuration
  consent:
    # Title displayed in the cookie consent banner
    title: Cookie consent
    # Description text shown in the cookie consent banner
    description: >-
      We use cookies to remember your visits and preferences, and to understand how you interact with the site.
      Your consent helps us improve the content and make this blog more useful.
    # Definition of cookies categories used by the site
    cookies:
      # Analytics cookies settings
      analytics:
        # Analytics service
        name: Google Analytics
        # Whether analytics cookies are enabled by default
        checked: true
    # List of action buttons in the consent banner
    actions:
      - accept
      - reject
      - manage
  # Analytics configuration
  analytics:
    # Analytics provider
    provider: google
    # Google Analytics tag ID
    property: G-QMWC3TXEVK
  # Environment variable
  environment: !ENV ENV
  # Generator notice
  generator: true
  # Social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/greengorych
      name: greengorych on GitHub
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/greengorych
      name: greengorych on LinkedIn

# Markdown extension settings
markdown_extensions:
  # Enables advanced syntax highlighting features
  - pymdownx.highlight:
      # Adds clickable anchors to line numbers
      anchor_linenums: true
      # Enables to wrap each line in a <span> element for styling
      line_spans: __span
      # Adds a CSS class with the language name for custom styling
      pygments_lang_class: true
  # Enables highlighting of inline code embedded in text
  - pymdownx.inlinehilite
  # Enables to directly embed external files or their fragments
  - pymdownx.snippets
  # Enables extended support for fenced code blocks, including nested ones
  - pymdownx.superfences

# Additional templates
extra_templates:
  # Template robots.txt
  - robots.txt
