name: Build and deploy site to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "docs/**"
      - "overrides/**"
      - "mkdocs.yml"
      - "requirements.txt"

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy:
    name: Build and deploy site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site sources
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ vars.PYTHON_VER }}

      - name: Install Wrangler
        run: |
          npm install -g wrangler@latest

      - name: Install Material for MkDocs and dependencies
        run: |
          pip install -r requirements.txt

      - name: Build site
        env:
          ENV: ${{ vars.ENV }}
          ENABLE_GROUP_PLUGINS: ${{ vars.ENABLE_GROUP_PLUGINS }}
        run: |
          mkdocs build --clean --site-dir ${{ vars.SITE_DIR }}

      - name: Generate IndexNow API Key File
        run: |
          echo "${{ secrets.INDEXNOW_API_KEY }}" > ${{ vars.SITE_DIR }}/${{ secrets.INDEXNOW_API_KEY }}.txt

      - name: Deploy site to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GH_TOKEN }}
          command: pages deploy ${{ vars.SITE_DIR }} --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }}
